### ISSUE TITLE
doctors exits out when folder has permission denied

### ISSUE THREAD

**Issue by chrismccoy** [wp-cli/doctor-command#104]
I noticed when a folder in wp-content is permission denied, doctor exits out.

    chris@steak:~/sites/domain.com$ wp doctor check --all
    Running checks  7  % [========>                                ]0:00 / 0:00
    Error: RecursiveDirectoryIterator::__construct(/home/chris/sites/domain.com/wp-
    content/galleryzip-cache): failed to open dir: Permission denied
    chris@steak:~/sites/domain.com$

**Comment by danielbachhuber** [comment]
Thanks for the report, @chrismccoy. I'll change this to a warning so the process can continue.
