### ISSUE TITLE
Fatal error: Class 'Spyc' not found in phar:///usr/local/bin/wp/vendor/wp-cli/mustangostang-spyc/includes/functions.php on line 31

### ISSUE THREAD

**Issue by jalavoy** [wp-cli/doctor-command#137]
We run a fairly custom build of this, so it's totally possible this is an issue on our end. But I'm totally unaware of how to find it.

Severity: Medium

Expected results: It works

Actual results: Getting this error when running doctor. Just updated to the latest release of doctor and profile. 

`Fatal error: Class 'Spyc' not found in phar:///usr/local/bin/wp/vendor/wp-cli/mustangostang-spyc/includes/functions.php on line 31`

We have the modules loaded to a custom location, can recreate with:
`export WP_CLI_PACKAGES_DIR=/opt/wp-cli-plugins ; /usr/local/bin/wp --allow-root --path=/home3/REDACTED/public_html doctor check --all`

WP-CLI Version: 1.4.1

Kernel:
`3.10.0-693.11.6.1.ELK.el6.x86_64`

PHP:
`PHP 5.4.45 (cli) (built: Oct  5 2015 15:35:12)
Copyright (c) 1997-2014 The PHP Group
Zend Engine v2.4.0, Copyright (c) 1998-2014 Zend Technologies
    with the ionCube PHP Loader (enabled) + Intrusion Protection from ioncube24.com (unconfigured) v10.1.1, Copyright (c) 2002-2017, by ionCube Ltd.
    with Zend Guard Loader v3.3, Copyright (c) 1998-2013, by Zend Technologies`

No suhosin.

WP Version:
`$wp_version = '4.8.5';`

WP-cli stat:
`  File: `/usr/local/bin/wp'
  Size: 4409743   	Blocks: 8624       IO Block: 4096   regular file
Device: 97dh/2429d	Inode: 997743      Links: 1
Access: (0755/-rwxr-xr-x)  Uid: (    0/    root)   Gid: (    0/    root)
Access: 2018-02-23 10:58:46.537376401 -0600
Modify: 2018-02-23 10:42:21.000000000 -0600
Change: 2018-02-23 10:58:44.807543311 -0600`

Packages:
`+------------------------+------------------+------------+-----------+----------------+
| name                   | authors          | version    | update    | update_version |
+------------------------+------------------+------------+-----------+----------------+
| wp-cli/doctor-command  | Daniel Bachhuber | v0.1.0     | available | dev-master     |
| wp-cli/profile-command |                  | dev-master | available | dev-master     |
+------------------------+------------------+------------+-----------+----------------+`

**Comment by danielbachhuber** [comment]
Which WP-CLI version are you running?

**Comment by jalavoy** [comment]
1.4.1, updated to reflect this.

I'm trying to build a 1.5.0 now to see if the problem goes away.

**Comment by danielbachhuber** [comment]
There were a couple prior instances of this but I can't recall the source:

* https://github.com/wp-cli/doctor-command/issues/111
* https://github.com/wp-cli/package-command/issues/12
* https://github.com/issues?utf8=%E2%9C%93&q=org%3Awp-cli+sort%3Aupdated-desc+spyc+

**Comment by jalavoy** [comment]
Heh, you're better at searching github than I, I couldn't find shit. I should probably learn the search terms.

**Comment by jalavoy** [comment]
yeah it's still broken with 1.5.0

**Comment by danielbachhuber** [comment]
Oh, I see. It looks like you're running doctor v0.1.0. Can you update doctor to latest with `wp package update`?

**Comment by jalavoy** [comment]
Hmm. it shouldn't be that version. I did a clean removal and reinstall in my repo before building the RPM. It's pulling from dev-master. 

Maybe my build is broken. Will look into that.

**Comment by jalavoy** [comment]
Yeah, 0.1.0 is what it's reading as the current version:

`# export WP_CLI_PACKAGES_DIR=/opt/wp-cli-plugins ; /usr/local/bin/wp --allow-root package update
Using Composer to update packages...
---
Loading composer repositories with package information
Updating dependencies
Resolving dependencies through SAT
Dependency resolution completed in 1.086 seconds
Analyzed 5357 packages to resolve dependencies
Analyzed 311446 rules to resolve dependencies
Package operations: 0 installs, 0 updates, 0 removals
Generating autoload files
---
Success: Packages updated.
# export WP_CLI_PACKAGES_DIR=/opt/wp-cli-plugins ; /usr/local/bin/wp --allow-root package list
+------------------------+------------------+------------+-----------+----------------+
| name                   | authors          | version    | update    | update_version |
+------------------------+------------------+------------+-----------+----------------+
| wp-cli/doctor-command  | Daniel Bachhuber | v0.1.0     | available | dev-master     |
| wp-cli/profile-command |                  | dev-master | available | dev-master     |
+------------------------+------------------+------------+-----------+----------------+`

Is this not accurate?

**Comment by danielbachhuber** [comment]
> Is this not accurate?

Nope. You'll need to update `wp-cli/doctor-command` to the latest `dev-master` because the fix hasn't been included in a tagged release yet.

**Comment by jalavoy** [comment]
How do I update to dev-master? Doing package update leaves me on v0.1.0, as shown in my previous comment.

**Comment by danielbachhuber** [comment]
Can you try `WP_CLI_PACKAGES_DIR=/opt/wp-cli-plugins wp package install wp-cli/doctor-command`, to force a re-install without a version constraint? It seems like there might be a version constraint in your `/opt/wp-cli-plugins/composer.json` file.

**Comment by jalavoy** [comment]
Yep that was it. Somehow the composer.json wasn't being updated by my rpm. All set now.

Thanks much for the assist.
