### ISSUE TITLE
Availability of this repo through Composer

### ISSUE THREAD

**Issue by Sotiris-k** [wp-cli/doctor-command#142]
It seems that this repo is not available through Packagist. 

I'm adding
`"wp-cli/doctor-command": "^2.0"`

and the resulting error is the following

`Problem 1
    - The requested package wp-cli/doctor-command could not be found in any version, there may be a typo in the package name.`

**Comment by swissspidy** [comment]
That is correct yeah. Not all repos here are on Packagist. Perhaps @schlessera can add this one.

In the meantime, just add this repository to your composer.json file so Composer will install the package directly from GitHub.

**Comment by schlessera** [comment]
The package was added to packagist: https://packagist.org/packages/wp-cli/doctor-command
