### ISSUE TITLE
WP-CLI Runs Out Of Memory During Installation

### ISSUE THREAD

**Issue by l0rdhamm3r** [wp-cli/doctor-command#157]
There seems to be an error when trying to install wp doctor saying WP-CLI ran out of memory. This is likely caused by the recent upgrade to WordPress 5.6 which had significant changes. The error in full can be found below:

```
# wp package install git@github.com:wp-cli/profile-command.git
Installing package wp-cli/profile-command (dev-master)
Updating /home/thisdomain/.wp-cli/packages/composer.json to require the package...
Registering git@github.com:wp-cli/profile-command.git as a VCS repository...
Using Composer to install the package...
---
Loading composer repositories with package information
Updating dependencies
Reverted composer.json.
WP-CLI ran out of memory. Please see https://bit.ly/wpclimem for further help.
```

This was replicated on two different servers in different environments.

**Comment by swissspidy** [comment]
As the error message says, please see https://bit.ly/wpclimem for further help.

WP-CLI uses Composer under the hood to manage WP-CLI packages. However, Composer is a bit of a memory hog, so you’ll need to increase your memory limit to accommodate it.

This is unrelated to WordPress core.
