### ISSUE TITLE
Stable version package shows fatal error

### ISSUE THREAD

**Issue by 1naveengiri** [wp-cli/doctor-command#166]
## Bug Report

**Describe the current, buggy behavior**

This commit has a fix (https://github.com/wp-cli/doctor-command/commit/fe41a0f04310304415dc667278d9f003fc6aa2d2)
which seems to be not updated in the stable version of the package. 

**Describe how other contributors can replicate this bug**

-  Install the package using this command `wp package install wp-cli/doctor-command:@stable` 

**Let us know what environment you are running this on**

```
OS:	Darwin 21.4.0 Darwin Kernel Version 21.4.0: Fri Mar 18 00:45:05 PDT 2022; root:xnu-8020.101.4~15/RELEASE_X86_64 x86_64
Shell:	/bin/zsh
PHP binary:	/Users/naveengiri/Library/Application Support/Local/lightning-services/php-8.0.0+2/bin/darwin/bin/php
PHP version:	8.0.0
php.ini used:	/Users/naveengiri/Library/Application Support/Local/run/spymP-7Ed/conf/php/php.ini
MySQL binary:	/Applications/Local.app/Contents/Resources/extraResources/lightning-services/mysql-8.0.16+6/bin/darwin/bin/mysql
MySQL version:	mysql  Ver 8.0.16 for macos10.14 on x86_64 (MySQL Community Server - GPL)
SQL modes:	ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION
WP-CLI root dir:	phar://wp-cli.phar/vendor/wp-cli/wp-cli
WP-CLI vendor dir:	phar://wp-cli.phar/vendor
WP_CLI phar path:	/Users/naveengiri/Local Sites/explorelocal/app/public
WP-CLI packages dir:	/Users/naveengiri/.wp-cli/packages/
WP-CLI global config:	/Applications/Local.app/Contents/Resources/extraResources/bin/wp-cli/config.yaml
WP-CLI project config:
WP-CLI version:	2.6.0
```

<img width="969" alt="Screenshot 2022-07-14 at 8 36 47 AM" src="https://user-images.githubusercontent.com/24760592/178889434-95b235d6-c865-4a2d-819b-4e026f489223.png">

**Comment by wojsmol** [comment]
Hi @1naveengiri 
Please post output of `wp package list` command

**Comment by 1naveengiri** [comment]
It seems I am using an outdated version. 
but I also tried using this command  `wp package update` 
I also tried re-installing the given package, but Nothing works.  


I do use this command to install it `wp package install wp-cli/doctor-command:@stable`

<img width="969" alt="Screenshot 2022-07-14 at 2 39 58 PM" src="https://user-images.githubusercontent.com/24760592/178947120-756d367a-8ee8-4fca-8a7d-18253fa72b8b.png">

am I missing anything? 

Thanks

**Comment by danielbachhuber** [comment]
@1naveengiri It appears you have an older version of `wp-cli/doctor-command` installed:

<img width="887" alt="image" src="https://user-images.githubusercontent.com/36432/180003151-832f87ea-ef02-4d8f-80a7-51f776b31a45.png">

I just ran `wp package install wp-cli/doctor-command:@stable` and the correct version (2.1.0) installs as expected:

```
wp package list
+---------------------------------+------------------+------------+-----------+----------------+
| name                            | authors          | version    | update    | update_version |
+---------------------------------+------------------+------------+-----------+----------------+
| wp-cli/doctor-command           | Daniel Bachhuber | v2.1.0     | none      |                |
| wp-cli/restful                  | Daniel Bachhuber | dev-master | available | 1.x-dev        |
| wp-cli/scaffold-package-command | Daniel Bachhuber | dev-master | available | 2.x-dev        |
+---------------------------------+------------------+------------+-----------+----------------+
```

I'd recommend deleting your package directory and re-installing all of your packages. You can delete the entire package directory with:

```
rm -r $(wp package path)
```
