### ISSUE TITLE
option to return headless results

### ISSUE THREAD

**Issue by joeldcanfield** [wp-cli/doctor-command#171]
Would love an option to return results without headings. For example the command 

`wp doctor check --all --spotlight --format=csv --fields=status,name`

returns

```
status,name
warning,cache-flush
```

but I would like to see

`warning,cache-flush`

Details: all result formats include headers. When piping results to other scripts, I don't want to have to explicitly ignore _"name,status"_ in the data I pass along, just a comma separated set of data.

**Comment by danielbachhuber** [comment]
Thanks for the suggestion, @joeldcanfield !

One of WP-CLI's philosophies is [composability](https://make.wordpress.org/cli/handbook/contributions/philosophy/#composability-is-always-a-good-idea). With this in mind, `tail` should get you what you want:

```
$ wp doctor check --all --spotlight --format=csv --fields=status,name | tail -n +2
```

I submitted a pull request against the handbook to document this for the next person: https://github.com/wp-cli/handbook/pull/434

**Comment by joeldcanfield** [comment]
again, excellent solution. thanks.
