### ISSUE TITLE
error only spotlight option

### ISSUE THREAD

**Issue by joeldcanfield** [wp-cli/doctor-command#172]
Would like an option to spotlight only errors, and not include warnings.

For myself, warnings are essentially meaningless. "Almost broken" doesn't warrant my attention.

**Comment by schlessera** [comment]
> "Almost broken" doesn't warrant my attention.
😆 

Yes, It makes sense to add a `--spotlight` flag. Are you open to providing a PR for this?

**Comment by joeldcanfield** [comment]
Beyond my ability. Wish I could; we're operating just outside my wheelhouse here and I'd love to expand said wheelhouse. (Brain issues slowing me down, hopefully temporarily.)

**Comment by joeldcanfield** [comment]
Arg. Please ignore that. I will return and reply more clearly and possibly even correctly.

**Comment by joeldcanfield** [comment]
I won't be able to make this happen (health issues.)

**Comment by ernilambar** [comment]
Looks like we already have `--spotlight` argument which displays `error` and `warning`.
Ref: https://github.com/wp-cli/doctor-command/pull/38

Is this enough or should we introduce new flag for error only?

**Comment by joeldcanfield** [comment]
for my purposes an error-only flag would be helfpul; I'd like to prevent scraping and scrapping pointless warnings in my results. as mentioned above, "almost broken" has no value in my use of the tool, only "all the way broken".

**Comment by ernilambar** [comment]
Rather than adding new flag for showing errors only, I have added argument to filter by status, like `--status=error` or `--status=warning`. This approach is what we have used in several WP CLI commands. 
PR - https://github.com/wp-cli/doctor-command/pull/188

**Comment by joeldcanfield** [comment]
matching existing code is perfect. excellent. thanks very much.
